spring.application.name=web.sportflow

# Configuration PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projet}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:psql}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:psql}

# Configuration of Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

weather.base-url=https://api.open-meteo.com/v1/forecast
app.data-initializer.enabled=${APP_DATA_INITIALIZER_ENABLED:false}
app.avatar-upload-dir=${APP_AVATAR_UPLOAD_DIR:upload_data/images/avatar}
app.badge-upload-dir=${APP_BADGE_UPLOAD_DIR:upload_data/images/badge}
geo.base-url=https://nominatim.openstreetmap.org
