spring.application.name=tp

# Configuration PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projet}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:psql}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:psql}

# Configuration of Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

weather.base-url=https://api.open-meteo.com/v1/forecast
geo.base-url=https://geocoding-api.open-meteo.com/v1/search